a=int(input("Enter the value of a:"))
b=int(input("Enter the value of b:"))
print("-"*50)
print("{}>{}={}".format(a,b,a>b))
print("{}>{}={}".format(a,b,b>a))
print("{}<{}={}".format(a,b,a<b))
print("{}<{}={}".format(a,b,b<a))
print("{}=={}={}".format(a,b,a==b))
print("{}!={}={}".format(a,b,a!=b))
print("{}>={}={}".format(a,b,a>=b))
print("{}>={}={}".format(a,b,b>=a))
print("{}<={}={}".format(a,b,a<=b))
print("{}<={}={}".format(a,b,a<=b))
print("-"*50)
